# setup-lb.yaml
---

  - hosts: loadbalancers
    become: true
    tasks:
        - name: Creating template
          template:
              src: ./lb-config.j2
              dest: /etc/httpd/conf.d/lb.conf
              owner: bin
              group: wheel
              mode: 064
          notify: Restart Apache
  
    handlers: 
      - name: Restart Apache
        service:
          name: httpd
          state: restarted